name: Approve And Merge Dependabot PR

on:
  workflow_call:
    inputs:
      branch:
        required: true
        description: 'The branch to checkout and work-on'
        type: string
      pull_request:
        required: false
        description: 'The Pull Request No.'
        type: string
      pull_request_title:
        required: false
        description: 'The Pull Request Title.'
        type: string
      auto-approve-merge:
        required: false
        description: 'Whether or not to approve merge the PR on success'
        type: string
      update-type:
        required: false
        description: 'Update type associated with dependabot PR'
        type: string
      sha:
        required: false
        description: 'SHA of the commit'
        type: string
    secrets:
      DEPENDABOT_APPROVE_MERGE_GITHUB_TOKEN:
        required: true

jobs:
  approve-merge:
    name: Approve And Merge Dependabot PR
    runs-on: ubuntu-latest
    # Perform the auto approve action only when the PR is raised by dependabot
    steps:
      - name: Echo Info
        run: echo "Approve and merge PR ${{ inputs.pull_request_title }} (${{ inputs.pull_request }})"    
      - name: Wait For PR Checks to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ inputs.branch }}
          running-workflow-name: 'Approve And Merge Dependabot PR'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Approve a Dependabot PR If Not Already Approved
        continue-on-error: true
        # Only if the check-approve-merge script return true (minor or patch versions and valid dependencies)
        if:  ${{ inputs.auto-approve-merge == 'true' }}
        run: gh pr review --approve
        env:
          GH_TOKEN: ${{secrets.DEPENDABOT_APPROVE_MERGE_GITHUB_TOKEN}}
      - name: Merge a Dependabot PR
        continue-on-error: true
        # Only if the check-approve-merge script return true (minor or patch versions and valid dependencies)
        if:  ${{ inputs.auto-approve-merge == 'true' }}
        # Auto merge the PR if all the check have passed
        run: gh pr merge --rebase --auto
        env:
          GH_TOKEN: ${{secrets.DEPENDABOT_APPROVE_MERGE_GITHUB_TOKEN}}
