name: Gradle Check

on:
  workflow_call:
    secrets:
      TEAMS_IDN_WH_URL:
        required: false

jobs:
  gradle-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Execute Gradle build
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check
    - name: codecov.io
      if: ${{!github.event.repository.private}}
      uses: codecov/codecov-action@v2.1.0
    - name: Gradle Dependency Check Analyze
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon dependencyCheckAnalyze
    - name: Notify Teams About Failure and Recovery
      if: ${{ secrets.TEAMS_IDN_WH_URL }}
      uses: interlok-tooling/notify-teams@v1
      with:
        teams-webhook-url: ${{ secrets.TEAMS_IDN_WH_URL }}
