# Use by test projects in github.com/interlok-testing
name: Gradle Check Test Project

on:
  workflow_call:
    secrets:
      NEXUS_REPO_PASSWORD:
        required: false
      TEAMS_IDN_WH_URL:
        required: false
      INTERLOK_LICENSE_KEY:
        required: false
    inputs:
      disable-dependency-check:
        description: 'Disable OWASP dependency check step'
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gradle-check:
    name: Gradle Check Test Project

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Execute Gradle build
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check
      env:
        ORG_GRADLE_PROJECT_repoUsername: ${{  secrets.NEXUS_REPO_PASSWORD && 'developer' || '' }}
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.NEXUS_REPO_PASSWORD }}
        INTERLOK_LICENSE_KEY: ${{  secrets.INTERLOK_LICENSE_KEY }}
    - name: Gradle Dependency Check Analyze
      if: ${{ inputs.disable-dependency-check != true }}
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon dependencyCheckAnalyze
    - name: Notify Teams About Failure and Recovery
      if: ${{ github.event.secrets.TEAMS_IDN_WH_URL }}
      uses: interlok-tooling/notify-teams@main
      with:
        teams-webhook-url: ${{ secrets.TEAMS_IDN_WH_URL }}
    - name: Upload Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: '**/build/reports/'
