name: Gradle Publish

on:
  workflow_call:
    secrets:
      NEXUS_REPO_PASSWORD:
        required: true
      TEAMS_IDN_WH_URL:
        required: true
    inputs:
      disable-dependency-check:
        description: 'Disable OWASP dependency check step'
        default: false
        required: false
        type: boolean
      runs-on:
        description: 'Runner lable, default to ubuntu-latest'
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:
  gradle-publish:
    name: Gradle Publish

    runs-on: ${{ inputs.runs-on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Execute Gradle build
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check
      env:
        ORG_GRADLE_PROJECT_repoUsername: deployment
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.NEXUS_REPO_PASSWORD }}
    - name: codecov.io
      if: ${{!github.event.repository.private}}
      uses: codecov/codecov-action@v3.1.3
    - name: Gradle Dependency Check Analyze
      if: ${{ inputs.disable-dependency-check != true }}
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon dependencyCheckAnalyze
    - name: Publish package
      if: success()
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon publish
      env:
        ORG_GRADLE_PROJECT_repoUsername: deployment
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.NEXUS_REPO_PASSWORD }}
    - name: Notify Teams About Failure and Recovery
      if: always()
      uses: interlok-tooling/notify-teams@main
      with:
        teams-webhook-url: ${{ secrets.TEAMS_IDN_WH_URL }}
